=== Trendafil158/XML-Project/Movie_catalog_XML_project/Project_Izpit_71888/src/XML-project/CatalogForFilms.dtd
<?xml encoding="UTF-8"?>

        <!ELEMENT catalog_for_movies (movie_studios,movies)>
        <!ELEMENT movie_studios (movie_studio)+>
        <!ELEMENT movies (movie)+>
        <!ELEMENT movie_studio (foundation,founder?,headquarters,(number_employees|owner)?,products,annual_income?,website,
                short_description)>
        <!ATTLIST movie_studio
                xmlns CDATA #FIXED ''
                studioID  #REQUIRED>
        <!ELEMENT movie (title_movie,duration,genre,year_of_issue,country,movie_studioMovie,imdb_rating,summary,director,actors,
                budget)>
        <!ATTLIST movie
                xmlns CDATA #FIXED ''
                unifier  #REQUIRED>
        <!ELEMENT foundation (#PCDATA)>
        <!ATTLIST foundation
                xmlns CDATA #FIXED ''
                century  #REQUIRED>
        <!ELEMENT founder (#PCDATA)>
        <!ELEMENT headquarters (#PCDATA)>
        <!ELEMENT number_employees (#PCDATA)>
        <!ELEMENT owner (#PCDATA)>
        <!ELEMENT products (#PCDATA)>
        <!ELEMENT annual_income (#PCDATA)>
        <!ATTLIST annual_income
                xmlns CDATA #FIXED ''
                currency CDATA #REQUIRED>
        <!ELEMENT website (#PCDATA)>
        <!ELEMENT short_description (#PCDATA)>
        <!ELEMENT title_movie (#PCDATA)>
        <!ATTLIST title_movie
                xmlns CDATA #FIXED ''
                lang  #REQUIRED>
        <!ELEMENT duration (#PCDATA)>
        <!ELEMENT genre (#PCDATA)>
        <!ELEMENT year_of_issue (#PCDATA)>
        <!ATTLIST year_of_issue
                xmlns CDATA #FIXED ''
                century  #REQUIRED>
        <!ELEMENT country (#PCDATA)>
        <!ELEMENT movie_studioMovie (#PCDATA)>
        <!ATTLIST movie_studioMovie
                xmlns CDATA #FIXED ''
                studioID  #REQUIRED>
        <!ELEMENT imdb_rating (#PCDATA)>
        <!ELEMENT summary (#PCDATA)>
        <!ELEMENT director (#PCDATA)>
        <!ELEMENT actors (actor)+>
        <!ELEMENT budget (#PCDATA)>
        <!ATTLIST budget
                xmlns CDATA #FIXED ''
                currency CDATA #REQUIRED>
        <!ELEMENT actor (#PCDATA)>

=== Trendafil158/XML-Project/Movie_catalog_XML_project/Project_Izpit_71888/src/XML-project/CatalogForFilmsForth.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE catalog_for_movies SYSTEM "CatalogForFilms.dtd">

<catalog_for_movies>

    <movie_studios>
        <movie_studio studioID="paramountPict">
            <foundation century = "20th">1912</foundation>
            <headquarters>Лос Анджелис, САЩ</headquarters>
            <products>Филми, комикси</products>
            <annual_income currency = "US dollar">6 900 000 000</annual_income>
            <website>www.paramount.com</website>
            <short_description>„Парамаунт Пикчърс“ е американска филмова компания, чиято централа се намира в Холивуд, САЩ.
                Компанията е основана май 1912 г. в Калифорния. Част е от мултимедийния концерн „Виаком“.</short_description>
        </movie_studio>
    </movie_studios>

    <movies>
        <movie unifier="forrestGump">
            <title_movie lang="en">Форест Гъмп</title_movie>
            <duration>142 минути</duration>
            <genre>Драма, Романтика</genre>
            <year_of_issue century = "20th">1994</year_of_issue>
            <country>САЩ</country>
            <movie_studioMovie studioID="paramountPict">Парамаунт Пикчърс</movie_studioMovie>
            <imdb_rating>8.8</imdb_rating>
            <summary>Филмът разказва историята на едно момче наречено Форест Гъмп, играно от Том Ханкс, което далеч не е интелигентно, но е присъствало на повечето важни моменти в
                Американската история. Филма ни показва, че не трябва да си задължително интелигентен за да успееш в живота. Всичко, което ти трябва е любов. Незабравим филм,
                който всеки трябва да гледа.</summary>
            <director>Робърт Земекис</director>
            <actors>
                <actor>Том Ханкс</actor>
                <actor>Сали Фийлд</actor>
                <actor>Гари Синийс</actor>
            </actors>
            <budget currency="US dollar">55 милиона</budget>
        </movie>

        <movie unifier="interstellar">
            <title_movie lang="en">Интерстелар</title_movie>
            <duration>169 минути</duration>
            <genre>Драма, Приключенски, Научна фантастика</genre>
            <year_of_issue century="21th">2014</year_of_issue>
            <country>САЩ, Великобритания, Канада</country>
            <movie_studioMovie studioID="paramountPict">Парамаунт Пикчърс</movie_studioMovie>
            <imdb_rating>8.5</imdb_rating>
            <summary>Интерстелар“ е най-монументалната творба на Кристофър Нолан до момента, а всеки, гледал „Генезис“, знае колко далече се простира въображението му.
                Сред сценаристите и продуцентите на филма е знаменитият физик Кип Торн, а първият зрител на „Интерстелар“ е бил Стивън Хокинг, който е дал пълното си одобрение.
                Защото това не е просто фантастика. Филмът е максимално достоверен от научна гледна точка и показаното в него е базирано на трудове на Торн и колегите му, които са
                доказали на теория много от сложните и напълно невероятни явления в „Интерстелар“. Гледан като една вероятна прогноза, филмът е още по-въздействащ.</summary>
            <director>Кристофър Нолан</director>
            <actors>
                <actor>Майкъл Кейн</actor>
                <actor>Ан Хатауей</actor>
            </actors>
            <budget currency="US dollar">165 милиона</budget>
        </movie>

    </movies>

</catalog_for_movies>

=== Trendafil158/XML-Project/Movie_catalog_XML_project/Project_Izpit_71888/src/XML-project/CatalogForFilmsSecond.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="TransformToTextMovies.xsl"?>
<!DOCTYPE catalog_for_movies SYSTEM "CatalogForFilms.dtd">

<catalog_for_movies>

    <movie_studios>

        <movie_studio studioID="columbiaPict">
            <foundation century = "20th">1918</foundation>
            <headquarters>Кълвър Сити, САЩ</headquarters>
            <products>Филми</products>
            <website>www.sonypictures.com</website>
            <short_description>„Кълъмбия Пикчърс“ е американско филмово студио, подразделение на „Сони Пикчърс Ентъртейнмънт“,
                което е от своя страна е собственост на „Сони“. То е едно от шестте най-големи студия в света заедно с Парамаунт, Уорнър Брос,
                Фокс, Уолт Дисни Пикчърс и Юнивърсъл. Централата на компанията се намира в Кълвър Сити.
                Създадено е през 1918 година, в резултат на започнало в края на 20-те години успешно сътрудничество с режисьора Франк Капра,
                студиото се превръща в едно от водещите в Холивуд. През 1982 година то е купено от компанията „Кока-Кола“, а след период на
                самостоятелност през 1987 – 1989 година – от японския конгломерат „Сони“.
            </short_description>
        </movie_studio>

        <movie_studio studioID="20thCen">
            <foundation century="20th">1935</foundation>
            <headquarters>Лос Анджелис, САЩ</headquarters>
            <number_employees>2300</number_employees>
            <products>Кино и телевизия</products>
            <website>www.20thcenturystudios.com</website>
            <short_description>Туентиът Сенчъри Студиос е американска филмова компания, собственост на Уолт Дисни Студиос, което е подразделение на Уолт Дисни Къмпани.
                В периода 1935-2020 г. компанията е известна като Туентиът Сенчъри Фокс, а през януари 2020 г. „Дисни“ променя името на Туентиът Сенчъри Студиос.
                Основана е през 1935 при сливането на компаниите Fox Film Corporation и Twentieth Century Pictures. Освен с производство на собствени филми, студиото се занимава и с разпространение на филми на по-малки независими компании.
            </short_description>
        </movie_studio>

    </movie_studios>

    <movies>

        <movie unifier="theGodFather">
            <title_movie lang="en">Кръстникът</title_movie>
            <duration>175 минути</duration>
            <genre>Драма, Криминален</genre>
            <year_of_issue century = "20th">1972</year_of_issue>
            <country>САЩ</country>
            <movie_studioMovie studioID="columbiaPict">Кълъмбия Пикчърс</movie_studioMovie>
            <imdb_rating>9.1</imdb_rating>
            <summary>Франсис Форд Копола представя сагата за фамилията Корлеоне с Марлон Брандов ролята на Кръстника Дон Вито. Копола рисува смразяващата картина на
                възхода на една сицилианска фамилия, на загубата на властта и влиянието и в Америка, както и предаването им от баща на син. Копола майсторски балансира
                сцените от семейния живот и отвратителния престъпен бизнес, в който са въвлечени членовете на семейството. Заснет по романа-бестселър на Марио Пузо,
                този брилянтен филм получи през 1972г. “Оскар” за най-добър филм.</summary>
            <director>Франсис Форд</director>
            <actors>
                <actor>Алфредо Джеймс Пачино</actor>
                <actor>Марлон Брендо</actor>
                <actor>Джеймс Кан</actor>
            </actors>
            <budget currency="US dollar">7 милиона</budget>
        </movie>

        <movie unifier="fightClub">
            <title_movie lang="en">Боен клуб</title_movie>
            <duration>139 минути</duration>
            <genre>Драма, Криминален</genre>
            <year_of_issue century="20th">1999</year_of_issue>
            <country>САЩ</country>
            <movie_studioMovie studioID="20thCen">Туентиът Сенчъри Студиос</movie_studioMovie>
            <imdb_rating>8.8</imdb_rating>
            <summary>Няколко години по-късно цялата този период приключва "със гръм". "Боен клуб" сваля шапка на своите предшественици ("Забриски пойнт", "Споразумението" на Елия Казан,
                "Ангелско сърце" на Алън Паркър), но се позовава само на "Форест гъмп", именно защото той е символът на края на епохата "Форест гъмп".</summary>
            <director>Дейвид Финчър</director>
            <actors>
                <actor>Брад Пит</actor>
                <actor>Хелена Бонам Картър</actor>
            </actors>
            <budget currency="US dollar">63 милиона</budget>
        </movie>

    </movies>

</catalog_for_movies>

=== Trendafil158/XML-Project/Movie_catalog_XML_project/Project_Izpit_71888/src/XML-project/CatalogForFilmsFifth.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE catalog_for_movies SYSTEM "CatalogForFilms.dtd">

<catalog_for_movies>

    <movie_studios>

        <movie_studio studioID="newLineCin">
            <foundation century = "20th">1967</foundation>
            <founder>Робърт Шайе</founder>
            <headquarters>Бърбанк, Калифорния</headquarters>
            <products>Филми, видеоигри</products>
            <website>www.newlinecinema.com</website>
            <short_description>New Line Productions, търгуваща като New Line Cinema, е американско студио за
                филмова продукция и лейбъл на подразделението Warner Bros. Pictures Group на Warner Bros. Entertainment. Основана е
                през 1967 г. от Робърт Шайе като независима компания за разпространение на филми, която по-късно се превръща във
                филмово студио. Той е придобит от Turner Broadcasting System през 1994 г. По-късно Търнър се слива с Time Warner
                през 1996 г., а New Line е обединен с Warner Bros. Pictures през 2008 г.  New Line продължава да разпространява
                своите филми, макар и като част от Warner Bros. Pictures, а не като отделна медийна компания наред с последната.
            </short_description>
        </movie_studio>

        <movie_studio studioID="mgm">
            <foundation century="20th">1924</foundation>
            <headquarters>Лос Анджелис, САЩ</headquarters>
            <number_employees>1440</number_employees>
            <products>Филми</products>
            <website>www.mgm.com</website>
            <short_description>Metro-Goldwyn-Mayerе американска компания, занимаваща се главно с производство и разпространение на филми и телевизионни сериали. От 1924 до 1942 г. е безспорният лидер в холивудската киноиндустрия.
                От 2005 г. собственик на компанията е Sony Pictures Entertainment. С това MGM става фактически сателит на Columbia Pictures, „перлата“ в короната на Sony.
                През ноември 2010 г. MGM съобщава, че е подала молба за съдебна защита от кредитори, което е равносилно на обявяване на фалит. Още през следващия месец обаче MGM заявява, че излиза от банкрута и даже съвместно с Columbia работи над филма „Zookeeper“.
            </short_description>
        </movie_studio>

    </movie_studios>

    <movies>

        <movie unifier="seven">
            <title_movie lang="en">Седем</title_movie>
            <duration>127 минути</duration>
            <genre>Драма, Криминален, Мистерия</genre>
            <year_of_issue century = "20th">1995</year_of_issue>
            <country>САЩ</country>
            <movie_studioMovie studioID="newLineCin">New Line Cinema</movie_studioMovie>
            <imdb_rating>8.6</imdb_rating>
            <summary>Основата на филма е разследване на серия кървави убийства. Всяко от убийствата наказва жертвите за определени смъртни грехове. В Библията са описани седем такива гряха.
                За да спрат веригата от маниакални убийства, започват разследване ветеранът от нюйорската полиция (Морган Фрийман) и неговият млад и енергичен партньор (Брад Пит).</summary>
            <director>Дейвид Финчър</director>
            <actors>
                <actor>Морган Фрийман</actor>
                <actor>Брад Пит</actor>
                <actor>Гуинет Полтроу</actor>
            </actors>
            <budget currency="US dollar">33 милиона</budget>
        </movie>

        <movie unifier="silenceOfLambs">
            <title_movie lang="en">Мълчанието на агнетата</title_movie>
            <duration>118 минути</duration>
            <genre>Драма, Криминален, Трилър</genre>
            <year_of_issue century="20th">1991</year_of_issue>
            <country>САЩ</country>
            <movie_studioMovie studioID="mgm">Метро-Голдуин-Майер</movie_studioMovie>
            <imdb_rating>8.6</imdb_rating>
            <summary>Психопат с псевдоним Бъфало Бил отвлича и убива млади жени в средния запад. ФБР агентът Кларис Старлинг (Фостър) получава задача да разговаря със затворник,
                чрез който да се опита да разбере как мисли убиеца. Затворникът е психиатърът Д-р Ханибал Лектър (Хопкинс), изключително умен и опасен канибал, който се
                съгласява да помогне на Кларис само при едно условие – да разбере всички подробности от личния й живот.</summary>
            <director>Джонатан Деми</director>
            <actors>
                <actor>Джоди Фостър</actor>
                <actor>Антъни Хопкинс</actor>
            </actors>
            <budget currency="US dollar">27 милиона</budget>
        </movie>

    </movies>

</catalog_for_movies>

=== Trendafil158/XML-Project/Movie_catalog_XML_project/Project_Izpit_71888/src/XML-project/CatalogForFilmsThird.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE catalog_for_movies SYSTEM "CatalogForFilms.dtd">

<catalog_for_movies>

    <movie_studios>

        <movie_studio studioID="warnerBros">
            <foundation century = "20th">1918</foundation>
            <headquarters>Бърбанк, Калифорния</headquarters>
            <owner>Тайм Уорнър</owner>
            <products>Филми, комикси</products>
            <website>www.wanerbros.com</website>
            <short_description>„Уорнър брадърс“ или само „Уорнър Брос.“ е американска развлекателна компания, базирана в град Бърбанк, щата Калифорния, САЩ.
                Тя е сред най-големите компании за производство на филми и телевизионни предавания. Понастоящем е дъщерна компания на конгломерата Тайм Уорнър, с главна квартира в Бърбанк, Калифорния, САЩ.
                Компанията се управлява от Бари Майер, председател на съвета на директорите. Други ключови фигури са Алън Хорн и Едуард Романо.
            </short_description>
        </movie_studio>

    </movie_studios>

    <movies>

        <movie unifier="theBlackKnight">
            <title_movie lang="en">Черният рицар</title_movie>
            <duration>152 минути</duration>
            <genre>Екшън, Драма, Криминален</genre>
            <year_of_issue century = "21th">2004</year_of_issue>
            <country>САЩ, Великобритания</country>
            <movie_studioMovie studioID="warnerBros">Уорнър Брадърс</movie_studioMovie>
            <imdb_rating>9.0</imdb_rating>
            <summary>В продължението на „Батман в началото" качулатият герой вдига залога в борбата с криминалния контингент. С помощта на лейтенант Джим Гордън и прокурора
                Харви Дент той смята да изчисти улиците от престъпността, тровеща града.Отначало сътрудничеството им се оказва ефективно, но скоро настава пълен хаос –
                появил се е нов гений на злото, известен сред ужасеното население под името Джокер. Това се оказа и последната роля на Хийт Леджър. В някои медии се появиха мнения,
                че изтощението от пълното себеотдаване на актьора е една от причините за нелепата му смърт.</summary>
            <director>Кристофър Нолан</director>
            <actors>
                <actor>Крисчън Бейл</actor>
                <actor>Маги Гилеенхал</actor>
                <actor>Майкъл Кейн</actor>
                <actor>Гари Олдман</actor>
            </actors>
            <budget currency="US dollar">185 милиона</budget>
        </movie>

        <movie unifier="inception">
            <title_movie lang="en">Генезис</title_movie>
            <duration>148 минути</duration>
            <genre>Екшън, Приключенски, Научна фантастика</genre>
            <year_of_issue century="21th">2010</year_of_issue>
            <country>САЩ, Великобритания</country>
            <movie_studioMovie studioID="warnerBros">Уорнър Брадърс</movie_studioMovie>
            <imdb_rating>8.7</imdb_rating>
            <summary>Дом Коб е опитен крадец, несъмнено най-добрият в опасното изкуство на извличане-крадене на ценни тайни от дълбокото подсъзнание в състояние на сън,
                когато мозъкът е най-уязвим. Необичайната способност на Коб го е направила много търсен в този коварен нов свят на корпоративен шпионаж, но го е превърнала в беглец,
                взимайки му всичко, което е обичал.Сега на Коб му се предлага шанс за спасение.</summary>
            <director>Кристофър Нолан</director>
            <actors>
                <actor>Леонардо ди Каприо</actor>
                <actor>Марион Котияр</actor>
            </actors>
            <budget currency="US dollar">160 милиона</budget>
        </movie>

    </movies>

</catalog_for_movies>

=== Trendafil158/XML-Project/Movie_catalog_XML_project/Project_Izpit_71888/src/XML-project/CatalogForFilmsFirst.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="VisualizeCatalogForFilmsFirst.xsl"?>
<!DOCTYPE catalog_for_movies SYSTEM "CatalogForFilms.dtd">

<catalog_for_movies>

    <movie_studios>

        <movie_studio studioID="CRE">
            <foundation century = "20th">1987</foundation>
            <founder>Мартин Шафър</founder>
            <products>Кинофилми</products>
            <website>www.castle_rock_entertainment.com</website>
            <short_description>Castle Rock Entertainment е американска филмова и телевизионна продуцентска компания,
                основана през 1987 г. от Мартин Шафър, режисьор Роб Рейнер , Андрю Шайнман , Глен Падник и Алън Хорн . Той е филиал на
                Warner Bros. , подразделение на AT и T е WarnerMedia.</short_description>
        </movie_studio>
    </movie_studios>

    <movies>

        <movie unifier = "shawshank">
            <title_movie lang = "en">Изкуплението Шоушенк</title_movie>
            <duration>142 минути</duration>
            <genre>Драма</genre>
            <year_of_issue century = "20th">1994</year_of_issue>
            <country>САЩ</country>
            <movie_studioMovie studioID = "CRE">Castle Rock Entertainment</movie_studioMovie>
            <imdb_rating>9.4</imdb_rating>
            <summary>40-те г. на 20 век. Анди Дюфрен е млад проспериращ банкер, чийто живот се променя драматично, когато е обвинен в убийството на жена си
                и нейният любовник и е осъден на доживотен затвор...Куражът на Анди и приятелството му с черноборсаджията на затвора „Ред” Рединг ще му помогнат
                да запази надеждата си жива. Това не е филм за отчаянието и самотата. Не е филм за изолацията. Това е филм за възкресените надежди, за приятелството,
                за мечтите и куражът на един мъж.</summary>
            <director>Франк Дарабонт</director>
            <actors>
                <actor>Тим Робинс</actor>
                <actor>Морган Фрийман</actor>
                <actor>Боб Гънтън</actor>
            </actors>
            <budget currency = "US dollar">25 милиона</budget>
        </movie>

        <movie unifier="greenRoad">
            <title_movie lang="en">Зеленият път</title_movie>
            <duration>189 минути</duration>
            <genre>Драма, Криминален, Фентъзи</genre>
            <year_of_issue century="20th">1999</year_of_issue>
            <country>САЩ</country>
            <movie_studioMovie studioID="CRE">Castle Rock Entertainment</movie_studioMovie>
            <imdb_rating>8.5</imdb_rating>
            <summary>През 1935 г. обитателите на затвора “Колд Маунтийн” кръщават пътеката към ешафода “Зеленият път” заради цвета на линолеума, с който е постлана.
                Пол Еджкомб (Том Ханкс) е главен надзирател в затвора, когато пристига нов осъден - Джон Кофи (Майкъл Кларк Дънкан) е обвинен в садистичното убийство на две малки момиченца.
                Въпреки огромният му ръст и ужасяващите престъпления, заради които е затворен, Кофи изглежда добър човек, който се държи по-скоро като невинно дете, отколкото като
                закоравял бандит.</summary>
            <director>Франк Дарабонт</director>
            <actors>
                <actor>Том Ханкс</actor>
                <actor>Бони Хънт</actor>
                <actor>Джеймс Кромуел</actor>
            </actors>
            <budget currency="US dollar">60 милиона</budget>
        </movie>

    </movies>

</catalog_for_movies>
